apiVersion: apps/v1
kind: Deployment
metadata:
  name: plaything-deployment
  labels:
    app: plaything
spec:
  replicas: 20
  selector:
    matchLabels:
      app: plaything
  template:
    metadata:
      labels:
        app: plaything
    spec:
      containers:
      - name: plaything
        image: plaything:1.0.0
        ports:
        - containerPort: 5000
