apiVersion: v1
kind: Pod
metadata:
  name: play-pod
  labels:
    app: plaything
spec:
  containers:
  - name: plaything
    image: plaything:1.0.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5000
      hostPort: 7500