apiVersion: v1
kind: Service
metadata:
  name: playing-svc
  labels:
    app: plaything
spec:
  selector:
    app: plaything
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
