apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-playing-svc"
  labels:
    app: plaything
spec:
  selector:
    app: plaything
  type: NodePort
  ports:
    - protocol: TCP
      port: 7500
      targetPort: 5000
      nodePort: 30027
